[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/submit-quote"
  to = "/.netlify/functions/submit-quote"
  status = 200

[[redirects]]
  from = "/api/save-internal-quote"
  to = "/.netlify/functions/save-internal-quote"
  status = 200

[[redirects]]
  from = "/api/accept-quote"
  to = "/.netlify/functions/accept-quote"
  status = 200

[[redirects]]
  from = "/quote"
  to = "/.netlify/functions/quote-page"
  status = 200

[[redirects]]
  from = "/api/get-quote-request"
  to = "/.netlify/functions/get-quote-request"
  status = 200

[[headers]]
  for = "/internalquote/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/quote"
  [headers.values]
